name: build

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21.0.1+12'

      - name: Build application
        working-directory: crac-spring-boot
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Checkpoint and Push Image
        working-directory: crac-spring-boot
        run: |
          docker build -t tsc/crac-spring-boot:builder .
          docker run -d --privileged --rm --name=crac-spring-boot --ulimit nofile=1024 -p 8080:8080 tsc/crac-spring-boot:builder
          sleep 10
          docker logs crac-spring-boot
          docker ps -a | grep crac-spring-boot
          docker commit --change='ENTRYPOINT ["/opt/app/entrypoint.sh"]' $(docker ps -qf "name=crac-spring-boot") tsc/crac-spring-boot:checkpoint
          docker push tsc/crac-spring-boot:checkpoint
          docker kill $(docker ps -qf "name=crac-spring-boot")